# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8imm0mks3d216lBvCnGUpDx6AQOxw_I

PROJECT NAME: FINANCIAL MARKET NEWS SENTIMENTS ANALYSIS

OBJECTIVE:This is a data(dummy)of finencial market Top25 news for the day and task is to train & predict model for overall sentiment analysis.

import library
"""

import pandas as pd

import numpy as np

"""import dataset"""

df=pd.read_csv(r'https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Financial%20Market%20News.csv',encoding='ISO.8859_1')

df.head()

df.info()

df.shape

df.columns

"""Get feature selection"""

''.join(str(x)for x in df.iloc[1,2:27])

df.index

len(df.index)

news=[]
for row in range (0,len(df.index)):news.append(''.join(str(x) for x in df.iloc[row,2:27]))

type(news)

news[0]

x=news

type(x)

"""Get feature text conversion to bag of words"""

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(lowercase=True,ngram_range=(1,1))

x=cv.fit_transform(x)

x.shape

y=df ['Label']

y.shape

"""Get train test split"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y,random_state=2529)

from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=200)

rf.fit(x_train,y_train)

y_pred=rf.predict(x_test)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

confusion_matrix(y_test,y_pred)

print(classification_report(y_test,y_pred))